# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# # set `default_language_version` need this version of Python existed on the computer
# default_language_version:
#   python: python3.10

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: no-commit-to-branch
      - id: check-added-large-files
      - id: check-toml
      - id: check-json
      - id: check-yaml
        args:
          - --unsafe
      - id: end-of-file-fixer
      - id: trailing-whitespace
  # ruff must before black
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.1
    hooks:
      - id: ruff
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
      - id: black
  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.332
    hooks:
      - id: pyright
        args: [-p, ".pre-commit-pyrightconfig.json"]  # ignore `reportMissingImports`
